[#78] add share function
zyrouge/symphony pull request #240
Opened 2023-08-15 17:55 UTC by Icarus-Xu

use system share intent to send music file uri to other app that recognize it

tested on Telegram, Wechat & QQ

2023-08-16 01:52 UTC, zyrouge requested changes

2023-08-16 01:52 UTC, zyrouge commented on app/src/main/java/io/github/zyrouge/symphony/ui/components/SongCard.kt
> +import android.util.Log
`Log` doesn't seem to be used anywhere. Kindly remove it.

2023-08-16 01:52 UTC, zyrouge commented on app/src/main/java/io/github/zyrouge/symphony/ui/components/SongCard.kt
> +                        "${context.symphony.t.ShareFailed} ${e.localizedMessage}",
Make it `Share failed (Error: <error message>)`.

2023-08-24 13:21 UTC, Icarus-Xu commented
done, sorry for the delay

2023-08-24 14:50 UTC, merged

2023-08-25 17:30 UTC, Icarus-Xu commented
TY