add customization ability to ForYou page
zyrouge/symphony pull request #58
Opened 2023-03-06 05:01 UTC by Icarus-Xu

add "Suggested album artists" to ForYou page and allow user to customize what they want to show on that page (Suggested albums / Suggested artists / Suggested album artists)

2023-03-07 13:26 UTC, zyrouge requested changes

2023-03-07 13:26 UTC, zyrouge commented on app/src/main/java/io/github/zyrouge/symphony/services/Settings.kt
> +            onChange.dispatch(SettingsKeys.homeLastTab)
Remove this line since it would be already called inside `setHomeLastTab`.

2023-03-08 02:52 UTC, Icarus-Xu commented
Removed in 561be73b6ec3ba5199b5d7aaa02a512c92865c98

2023-03-08 02:53 UTC, Icarus-Xu commented on app/src/main/java/io/github/zyrouge/symphony/services/Settings.kt
> +            onChange.dispatch(SettingsKeys.homeLastTab)
Removed in 561be73b6ec3ba5199b5d7aaa02a512c92865c98

2023-03-09 01:33 UTC, zyrouge commented
I'd have to rebase this once I push my local branch to here, kindly wait for that. Also, thank you for contributing.

2023-03-09 01:34 UTC, zyrouge approved these changes

2023-03-09 07:59 UTC, Icarus-Xu commented
> I'd have to rebase this once I push my local branch to here, kindly wait for that. Also, thank you for contributing.

No problem, take your time.

2023-03-12 07:27 UTC, merged