Feature: Album duration
zyrouge/symphony pull request #666
Opened 2024-11-15 13:56 UTC by sevonj

Closes #588 
 
## Changes
- Albums now track total duration
- The duration is shown in album view

<details>
<summary> screenshot </summary>

![image](https://github.com/user-attachments/assets/23db114f-21ce-4270-9ae9-e65248076a54)

</details>
 
## Comments
**Possible further improvements:**  
- I think the UI would look nicer if the menu moved to the top right corner.  
  <details>
  <summary> mockup </summary>

  ![image](https://github.com/user-attachments/assets/1c6ca5bc-573a-4102-ba82-9e08db08b1dd)
  </details>
- Custom formatting; don't show seconds if duration >= 1 min 

**Alternatives:**
Display the duration in the top bar along with song count.

2024-11-18 15:17 UTC, Currrupted commented
I think both variants look neat, though I'd expect the menu to have that design/position everywhere.

2024-11-19 18:02 UTC, zyrouge requested changes

2024-11-21 11:48 UTC, sevonj commented on app/src/main/java/io/github/zyrouge/symphony/ui/components/GenericGrooveBanner.kt
> +                    .padding(defaultHorizontalPadding, 32.dp, 0.dp, 12.dp)
![image](https://github.com/user-attachments/assets/43bdf785-b0db-425c-914c-1473f2bede5a)

It felt like too much.

2024-11-23 17:44 UTC, sevonj commented
I tested the ui with all kinds of strings, and got more consistent results with a two-column layout instead of fiddling with individual row items.

![Screenshot From 2024-11-23 19-33-20](https://github.com/user-attachments/assets/cb60f6a2-39d6-41c2-972f-385ce22a9659)

2024-11-23 17:57 UTC, zyrouge commented
I think the design would be much better if we moved the duration to the left. The text near the more options icons looks uncomfortable since they are not aligned.

2024-11-23 18:00 UTC, zyrouge requested changes

2024-11-23 18:00 UTC, zyrouge commented on app/src/main/java/io/github/zyrouge/symphony/ui/view/Album.kt
> +                Column(
Revert this and add duration as a row.

2024-11-23 18:04 UTC, sevonj commented
> I think the design would be much better if we moved the duration to the left. The text near the more options icons looks uncomfortable since they are not aligned.

![Screenshot From 2024-11-23 20-03-31](https://github.com/user-attachments/assets/941d8ffa-7601-403f-a16f-3b93e13d1d5b)

Like a row?

2024-11-23 18:08 UTC, sevonj commented
Maybe the duration could be slightly less bright colored to make it less awkward.

2024-11-23 18:08 UTC, zyrouge commented
> > I think the design would be much better if we moved the duration to the left. The text near the more options icons looks uncomfortable since they are not aligned.
> 
> ![Screenshot From 2024-11-23 20-03-31](https://private-user-images.githubusercontent.com/100710152/389217499-941d8ffa-7601-403f-a16f-3b93e13d1d5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODU1NTMsIm5iZiI6MTczMjM4NTI1MywicGF0aCI6Ii8xMDA3MTAxNTIvMzg5MjE3NDk5LTk0MWQ4ZmZhLTc2MDEtNDAzZi1hMTZmLTNiOTNlMTNkMWQ1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxODA3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjIxYWJhYjIxMzIxNGQwZTI4MTkwMDE0ODYxZmJmOGEyNjk4MDEzZjI0OGU3YzliMGVlYzgyNzNhYjM0MTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZA4DeNa_kbzeuj0qae1SSwCEDILA6iUTNKn6gpXVGW8)
> 
> Like a row?

Yup, that looks for now. We could make changes to the UI in the future.

2024-11-23 18:10 UTC, zyrouge commented
> Maybe the duration could be slightly less bright colored to make it less awkward.

I was thinking the same but we might add more metadata such as album start/end year which would make it look less awkward.

2024-11-23 18:11 UTC, sevonj commented
With the current design, I'd add the metadata to the same row as in

> 2024-2025 | 2h 49m

2024-11-23 18:16 UTC, zyrouge commented
> With the current design, I'd add the metadata to the same row as in
> 
> > 2024-2025 | 2h 49m

Yeah, that is how I meant. Don't add them in this PR yet.

2024-11-23 18:17 UTC, sevonj commented
This should be OK to merge now.

2024-11-23 18:19 UTC, zyrouge approved these changes

2024-11-23 18:20 UTC, zyrouge commented
LGTM!

2024-11-23 18:20 UTC, merged

2025-01-04 15:31 UTC, Currrupted commented
I like the way the duration was implemented. However, I have noticed that the album duration includes milliseconds and thus isn't that intuitive.  The duration isn't 45 minutes and 32 seconds (as an example), but 45m 32.124s. Wouldn't it be better to round the duration to the full integer? Alternatively, maybe the digits after the decimal point could be hidden, somehow?

2025-01-04 15:55 UTC, sevonj commented
> I like the way the duration was implemented. However, I have noticed that the album duration includes milliseconds and thus isn't that intuitive. The duration isn't 45 minutes and 32 seconds (as an example), but 45m 32.124s. It doesn't really make sense, because normally the length of a song isn't expressed in milliseconds. Wouldn't it be better to round the duration to the full integer? Alternatively, maybe the digits after the decimal point could be hidden, somehow? @sevonj

I mentioned in the top PR comment that the formatting could be improved. If the default also shows milliseconds in some cases, a custom formatter is more necessary than I thought.

2025-01-04 16:08 UTC, Currrupted commented
> > I like the way the duration was implemented. However, I have noticed that the album duration includes milliseconds and thus isn't that intuitive. The duration isn't 45 minutes and 32 seconds (as an example), but 45m 32.124s. It doesn't really make sense, because normally the length of a song isn't expressed in milliseconds. Wouldn't it be better to round the duration to the full integer? Alternatively, maybe the digits after the decimal point could be hidden, somehow? @sevonj
> 
> I mentioned in the top PR comment that the formatting could be improved. If the default also shows milliseconds in some cases, a custom formatter is more necessary than I thought.

That makes sense! I must have missed that. For reference, this is what it looks like for me:
![signal-2025-01-04-17-03-57-680](https://github.com/user-attachments/assets/4305b05f-111c-4be9-bb2c-53920219dfa4)

I don't know if there is something wrong with my files or the codec, if the duration is so weird. But the format is like this everywhere for me.

2025-01-04 16:22 UTC, zyrouge commented
> > > I like the way the duration was implemented. However, I have noticed that the album duration includes milliseconds and thus isn't that intuitive. The duration isn't 45 minutes and 32 seconds (as an example), but 45m 32.124s. It doesn't really make sense, because normally the length of a song isn't expressed in milliseconds. Wouldn't it be better to round the duration to the full integer? Alternatively, maybe the digits after the decimal point could be hidden, somehow? @sevonj
> > 
> > 
> > I mentioned in the top PR comment that the formatting could be improved. If the default also shows milliseconds in some cases, a custom formatter is more necessary than I thought.
> 
> That makes sense! I must have missed that. For reference, this is what it looks like for me: ![signal-2025-01-04-17-03-57-680](https://private-user-images.githubusercontent.com/13292623/400149951-4305b05f-111c-4be9-bb2c-53920219dfa4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMDc3NTcsIm5iZiI6MTczNjAwNzQ1NywicGF0aCI6Ii8xMzI5MjYyMy80MDAxNDk5NTEtNDMwNWIwNWYtMTExYy00YmU5LWJiMmMtNTM5MjAyMTlkZmE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE2MTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTYzYmVlYzE4MDJjNzJmZDQ2OTc1MDE4ZTI4N2NjNjgzMWQzNGExMDAwMzAxMTNlYWI4YTczMGIxMjdkMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-39V7OFrAxUew86g4Bz-cg7YhXf_bDSVQQlSJOLwpXU)
> 
> I don't know if there is something wrong with my files or the codec, if the duration is so weird. But the format is like this everywhere for me.

I've did not have that issue either. I guess the simplest fix would be to convert them to milliseconds to seconds before displaying.