Feat: Album year display
zyrouge/symphony pull request #681
Opened 2024-11-24 11:04 UTC by sevonj

Closes #587 

![image](https://github.com/user-attachments/assets/8849102a-ca3a-44f1-9309-43684ca1f767)

2024-11-24 11:31 UTC, zyrouge requested changes

2024-11-24 11:31 UTC, zyrouge commented on app/src/main/java/io/github/zyrouge/symphony/ui/view/Album.kt
> +                    Text(
Add a separator that is small circle in shape which is the same color as the text but with a lower opacity. Should make the design much better.

2024-11-24 12:12 UTC, sevonj commented on app/src/main/java/io/github/zyrouge/symphony/ui/view/Album.kt
> +                    Text(
![image](https://github.com/user-attachments/assets/01265ed2-d248-42a7-affa-3a41cd5efc99)
![image](https://github.com/user-attachments/assets/3ab92ccd-f0eb-4302-b45f-36ae87e660f4)

2024-11-27 07:51 UTC, zyrouge approved these changes

2024-11-27 07:51 UTC, merged